controller:
  image:
    repository: "jenkins/jenkins"
    tag: "lts-jdk25"

  resources:
    requests:
      cpu: "200m"
      memory: "1024Mi"
    limits:
      cpu: "1000m"
      memory: "2048Mi"

  jenkinsUrl: "https://jenkins.ahmadfaisal.space/"

  persistence:
    enabled: true
    storageClass: "local-path"
    size: "8Gi"

  admin:
    username: "admin"

  serviceType: ClusterIP
  servicePort: 8080

  installPlugins:
    # Defaults
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.9.0
    - configuration-as-code:2037.v8e5349845172
    # Additions
    - pipeline-stage-view:2.39
    - pipeline-graph-view:763.v0e91db_e845ee

agent:
  enabled: true
  image:
    repository: "jenkins/inbound-agent"
    tag: "jdk25"
